

# web server config
listen_host: '0.0.0.0'
listen_port: 5004

# redis config
redis_persist:
  "host": "localhost"
  "port": 6379
  "db_number": 1
  "expire": 15768000 # 6 meses de retención

redis_cache:
  "host": "localhost"
  "port": 6379
  "db_number": 0
  "expire": 10
  
  
#short url host
# ejemplo myhost = "http://myhost.com".  Si se deja en blanco lo completa automáticamente con la ip de la interfaz eth0
myhost: ""
